In [1]:
import pandas as pd; import os; import time; import re;
import numpy as np; import random; import copy; import sys

In [2]:
# read review data
data = pd.read_csv('sorted_corpus.csv')

F:\anaconda\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,

In [4]:
data.head(10)

business_id  stars             0          1        2       3  \
0           18    1.0         place        doe    exist  number   
1           18    5.0       havenot       year     best   pizza   
2           18    5.0        review        doe    place    even   
3           24    1.0  disappointed     server      get    good   
4           24    3.0       service     pretty     good   price   
5           24    1.0           wow      shame    greek    gone   
6           24    1.0         drink  selection  lacking  wanted   
7           24    2.0       usually       half    price    wing   
8           24    2.0          ever      since    place    sold   
9           24    4.0      probably       best     wing    city   

                 4        5          6        7 ...   512  513  514  515  516  \
0             left  massage  parlorlol      NaN ...   NaN  NaN  NaN  NaN  NaN   
1         daughter    would      piece    pizza ...   NaN  NaN  NaN  NaN  NaN   
2            still    exist      loved  growing ...   NaN  NaN  NaN  NaN  NaN   
3          patient   upbeat     didnot     know ...   NaN  NaN  NaN  NaN  NaN   
4           little     high       food  quality ...   NaN  NaN  NaN  NaN  NaN   
5  qualitycustomer  service       good    staff ...   NaN  NaN  NaN  NaN  NaN   
6            girly    drink     pretty     much ...   NaN  NaN  NaN  NaN  NaN   
7             deal   longer    offered  ordered ...   NaN  NaN  NaN  NaN  NaN   
8           summer  service       food  quality ...   NaN  NaN  NaN  NaN  NaN   
9            cheap     beer        ive    going ...   NaN  NaN  NaN  NaN  NaN   

   517  518  519  520  521  
0  NaN  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  
5  NaN  NaN  NaN  NaN  NaN  
6  NaN  NaN  NaN  NaN  NaN  
7  NaN  NaN  NaN  NaN  NaN  
8  NaN  NaN  NaN  NaN  NaN  
9  NaN  NaN  NaN  NaN  NaN  

[10 rows x 524 columns]

In [5]:
index=data['business_id']
index={}.fromkeys(index).keys()
index=list(index)

In [6]:
corpus = []
j=0
for i in range(100):
    print(i)
    temp = []
    while j < data.shape[0]:
        if not data['business_id'][j] == index[i]:
            break
        for k in range(2,524):
            if not data.loc[j].notnull()[k]:
                break
            elif data.loc[j].notnull()[k]:
                temp.append(data.loc[j][k])
        j = j+1
    corpus.append(temp)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [599]:
len(corpus)


100

In [35]:
import lda

In [601]:
len(corpus[0])

0

In [604]:
print(corpus[1])

[]


In [34]:
#create wordtoid, idtoword, document
def createDict(cut_docs):
        word2id = dict()
        wordnum = 0
        for i, doc in enumerate(cut_docs):
            for j, word in enumerate(doc):
                wordnum += 1
                if word not in word2id:
                    word2id[word] = len(word2id)
                cut_docs[i][j] = word2id[word]
        return word2id, dict(zip(word2id.values(), word2id.keys())), cut_docs, wordnum


In [8]:
# LDA WITH GIBBS SAMPLING
# Set global variables
max_iter_num = 300

# intialize some parameters
k = 20 # number of topics, modify it when necessary
alpha = .1 
beta = .01

#wordsum= number of words in individual documents, list
#nD = total number of ducuments 
#D=len(corpora) total number of documents

In [36]:
model=lda.LDA(n_topics=20,n_iter=300,random_state=1)

In [ ]:
model.fit(data)

In [9]:
origincorpus=copy.deepcopy(corpus)

In [10]:
word2id,id2word,cutdocs,wordnum=createDict(corpus)

In [14]:
len(id2word)

16669

In [19]:
z.shape
theme

5

In [31]:
# initial 
D=len(corpus)
K=20
V=len(id2word)
nd = np.array(np.zeros([D, K]), dtype=np.int32)
nw = np.array(np.zeros([K, V]), dtype=np.int32)
ndsum = np.array(np.zeros([D]), dtype=np.int32)
nwsum = np.array(np.zeros([K]), dtype=np.int32)
z = np.array(np.zeros([D, V]), dtype=np.int32)
theta = np.ndarray([D, K])
phi = np.ndarray([K, V])

In [32]:
#id_cut_docs
for i, doc in enumerate(cutdocs):
    #print(i)
    for j, word_id in enumerate(doc):
        #print(j)
        theme = random.randint(0, k-1)
        z[i,j] = theme
        nd[i,theme] += 1
        nw[theme,word_id] += 1
        ndsum[i] += 1
        nwsum[theme] += 1

IndexError: index 16669 is out of bounds for axis 1 with size 16669

In [23]:
z

array([[ 7,  5,  3, ...,  0,  0, 18],
       [17, 18, 19, ...,  0,  0,  8],
       [ 2,  8,  8, ...,  0,  0, 16],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [519]:
print(nwsum)

[774206 773119 773140 773737 773394 773403 772998 772910 773904 774369
 774325 774814 774057 774101 773730 774042 773585 775315 773923 773706]


In [24]:
def reSamppling(nd, nw, ndsum, nwsum):
        pk = np.ndarray([K])
        for i in range(K):
            # gibbs采样公式
            pk[i] = float(nd + alpha)*(nw +beta)/\
                    ((ndsum + alpha*K)*(nwsum + beta*V))
            if i > 0:
                pk[i] += pk[i-1]

        # 轮盘方式随机选择主题
        u = random.random()*pk[K-1]
        for k in range(len(pk)):
            if pk[k]>=u:
                return k

In [25]:
def updatePara():
        for d in range(D):
            for k in range(K):
                theta[d,k] = float(nd[d,k] + alpha)/\
                                (ndsum[d] + alpha*K)

        for k in range(K):
            for v in range(V):
                phi[k,v] = float(nw[k,v] + beta)/\
                                (nwsum[k] + beta*K)


In [28]:
#gibbs sampling
for iter in range(max_iter_num):
    for i, doc in enumerate(cutdocs):
        for j, word_id in enumerate(doc):
            theme = z[i,j]
            nd_t = nd[i,theme] - 1
            nw_t = nw[theme,word_id] - 1
            ndsum_t = ndsum[i] - 1
            nwsum_t = nwsum[theme] - 1
            # 重新给词选择新的主题
            new_theme = reSamppling(nd_t, nw_t, ndsum_t, nwsum_t)
            
            nd[i,theme] -= 1
            nw[theme,word_id] -= 1
            nwsum[theme] -= 1
                    
            nd[i,new_theme] += 1
            nw[new_theme,word_id] += 1
            nwsum[new_theme] += 1
            z[i,j] = new_theme
    sys.stdout.write('\rIteration:{0} done!'.format(iter+1))
    sys.stdout.flush()



IndexError: index 16669 is out of bounds for axis 1 with size 16669

In [27]:
import sys

In [472]:
updatePara()

[[3 2 4 ... 2 0 3]
 [0 0 1 ... 3 0 1]
 [1 0 2 ... 4 3 1]
 ...
 [2 2 2 ... 2 3 0]
 [0 1 0 ... 0 3 0]
 [1 2 2 ... 2 0 0]]


(292, 20)

In [473]:
# predict topic
def predict(new_doc, isupdate=False):
        new_cut_doc = cut(new_doc)[0]
        new_cut_id_doc = list()
        for word in new_cut_doc:
            if word in word2id:
                new_cut_id_doc.append(word2id[word])

        # 原为D*K,现在为1*K
        new_nd = np.zeros([K], dtype=np.int32)
        # 原为K*V,现在依然为K*V
        new_nw = copy.deepcopy(nw)
        # 原为1*D,现为1
        new_ndsum = 0
        # 原为1*K,现为1*K
        new_nwsum = copy.deepcopy(nwsum)
        # 当前文档的各个词的主题,1*V
        new_z = np.zeros([V]);

        # 类似于initial函数
        for j, word_id in enumerate(new_cut_id_doc):
            theme = random.randint(0, K-1)
            new_nd[theme] += 1
            new_nw[theme, word_id] += 1
            new_ndsum += 1
            new_nwsum[theme] += 1
            new_z[j] = theme

        # 类似于gibbsSampling函数
        for iter in range(iteration):
            for j, word_id in enumerate(new_cut_id_doc):
                theme = new_z[j]
                cur_nd = new_nd[theme] -1
                cur_nw = new_nw[theme,word_id] - 1
                cur_ndsum = new_ndsum - 1
                cur_nwsum = new_nwsum[theme] - 1

                new_theme = reSamppling(cur_nd, cur_nw, cur_ndsum, cur_nwsum)

                new_z[j] = new_theme
                new_nd[theme] -= 1
                new_nw[theme, word_id] -= 1
                new_nwsum[theme] -= 1

                new_nd[new_theme] += 1
                new_nw[new_theme,word_id] += 1
                new_nwsum[new_theme] += 1

            sys.stdout.write('\rIteration:{0} done!'.format(iter+1))
            sys.stdout.flush()

        # 更新theta参数,即再加1行
        new_theta = np.ndarray([K])
        for k in range(K):
            new_theta[k] = float(new_nd[k] + alpha)/\
                            (new_ndsum + alpha*K)

        # 若更新phi参数,即更新phi矩阵中所有的参数
        # 则需要同时更新theta,z,nw,nd,nwsum,ndsum
        # 也可以不更新,即参数和原来没预测之前一样
        if isupdate:
            for k in range(self.K):
                for v in range(self.V):
                    phi[k,v] = float(new_nw[k,v] + beta)/\
                                    (new_nwsum[k] + beta*K)

        # 返回该文档的各个主题出现概率,以及每个词对应的主题
        return new_theta, new_z

In [495]:
# 返回各个主题的top词汇
def getTopWords(top_num=20):
    with open('./topwords.csv', 'w') as fw:
         for k in range(K):
                top_words = np.argsort(-phi[k,:])[:top_num]
                top_words = [id2word[word] for word in top_words]
                top_words = '\t'.join(top_words)
                res = 'topic{0}\t{1}'.format(k, top_words)
                fw.write(res+'\n')
                print (res)

In [490]:
# 返回文档前几个topic中的前几个词
def getTopTopics(top_topic=5, top_word=5):
        with open('./toptopics.csv', 'w') as fw:
            for d in range(D):
                top_topics = np.argsort(-theta[d,:])[:top_topic]
                print ('document{0}:'.format(d))
                for topic in top_topics:
                    top_words_id = np.argsort(-phi[topic,:])[:top_word]
                    top_words = [id2word[word] for word in top_words_id]
                    top_words = '\t'.join(top_words)
                    res = 'topic{0}\t{1}'.format(topic, top_words)
                    fw.write(res+'\n')
                    print (res)
                fw.write('\n')

In [491]:
print(getTopTopics())

document0:
topic17	pizza	great	place	food	good
topic3	pizza	great	base	good	food
topic18	pizza	service	place	base	one
topic7	pizza	good	base	place	service
topic12	pizza	service	one	food	beer
document1:
topic4	pizza	food	place	one	fresh
topic12	pizza	service	one	food	beer
topic8	pizza	salad	place	base	great
topic0	pizza	base	really	salad	one
topic1	pizza	place	back	great	good
document2:
topic0	pizza	base	really	salad	one
topic11	pizza	place	great	food	one
topic5	pizza	place	service	food	great
topic10	pizza	great	place	love	base
topic16	pizza	great	place	base	food
document3:
topic15	pizza	great	base	place	good
topic19	pizza	base	good	great	place
topic17	pizza	great	place	food	good
topic7	pizza	good	base	place	service
topic12	pizza	service	one	food	beer
document4:
topic3	pizza	great	base	good	food
topic1	pizza	place	back	great	good
topic17	pizza	great	place	food	good
topic14	pizza	place	good	time	great
topic9	pizza	great	time	delicious	food
document5:
topic18	pizza	service	place	base	one


topic4	pizza	food	place	one	fresh
topic5	pizza	place	service	food	great
topic0	pizza	base	really	salad	one
topic16	pizza	great	place	base	food
topic12	pizza	service	one	food	beer
document164:
topic19	pizza	base	good	great	place
topic14	pizza	place	good	time	great
topic16	pizza	great	place	base	food
topic2	pizza	great	place	good	food
topic6	pizza	place	food	great	owner
document165:
topic0	pizza	base	really	salad	one
topic6	pizza	place	food	great	owner
topic1	pizza	place	back	great	good
topic15	pizza	great	base	place	good
topic3	pizza	great	base	good	food
document166:
topic0	pizza	base	really	salad	one
topic6	pizza	place	food	great	owner
topic13	pizza	great	place	service	base
topic1	pizza	place	back	great	good
topic4	pizza	food	place	one	fresh
document167:
topic15	pizza	great	base	place	good
topic17	pizza	great	place	food	good
topic8	pizza	salad	place	base	great
topic0	pizza	base	really	salad	one
topic9	pizza	great	time	delicious	food
document168:
topic1	pizza	place	back	great	good
topic

In [496]:
print(getTopWords())

topic0	pizza	base	really	salad	one	great	fresh	good	service	oil	place	delicious	time	made	food	organic	night	restaurant	menu	back
topic1	pizza	place	back	great	good	base	really	experience	one	salad	oil	love	fresh	owner	definitely	also	flavor	prosciutto	super	time
topic2	pizza	great	place	good	food	service	base	nice	try	crust	salad	amazing	new	one	friendly	olive	super	like	also	neighborhood
topic3	pizza	great	base	good	food	place	like	service	owner	friendly	time	lunch	got	fresh	ordered	super	get	one	sauce	way
topic4	pizza	food	place	one	fresh	perfect	great	server	amazing	awesome	ordered	good	come	service	owner	really	oil	crust	small	friendly
topic5	pizza	place	service	food	great	base	one	little	good	fresh	pizzeria	restaurant	time	make	phoenix	loved	staff	day	really	like
topic6	pizza	place	food	great	owner	back	base	try	good	night	tomato	staff	amazing	organic	ingredient	like	dinner	table	favorite	well
topic7	pizza	good	base	place	service	one	fresh	first	amazing	friendly	experience	time	f